[package]
name = "roles"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet.workspace = true
openzeppelin_access.workspace = true
openzeppelin_introspection.workspace = true
onchain_id_starknet.workspace = true
token =  { path = "../token"}
registry = { path = "../registry"}
mocks = { path = "../mocks"}
factory = { path = "../factory"}

[dev-dependencies]
snforge_std.workspace = true
openzeppelin_token.workspace = true
openzeppelin_security.workspace = true

[[target.starknet-contract]]
sierra = true
build-external-contracts = ["onchain_id_starknet::*", "registry::*", "token::*", "compliance::*", "factory::*", "mocks::*"]

[tool]
fmt.workspace = true

[lib]
name= "roles"