[package]
name = "roles"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet.workspace = true
openzeppelin_access.workspace = true
openzeppelin_introspection.workspace = true
token =  { path = "../token"}
registry = { path = "../registry"}
onchain_id_starknet.workspace = true
mocks = { path = "../mocks"}

[dev-dependencies]
snforge_std.workspace = true

[[target.starknet-contract]]
sierra = true
build-external-contracts = ["mocks::*"]

[tool]
fmt.workspace = true

[lib]
name= "roles"