[workspace]
members = [
    "crates/*",
]

[workspace.package]
name = "erc3643_starknet"
version = "0.1.0"
edition = "2024_07"
description = "Implementation of the ERC-3643 T-REX protocol on Starknet."
cairo-version = "2.9.2"
scarb-version = "2.9.2"
readme = "README.md"

[workspace.dependencies]
assert_macros = "2.9.2"
starknet = "2.9.2"
snforge_std = "0.35.1"
openzeppelin_token =  "0.20.0"
openzeppelin_access = "0.20.0"
openzeppelin_introspection = "0.20.0"
openzeppelin_upgrades = "0.20.0"
openzeppelin_security = "0.20.0"

[workspace.tool.fmt]
sort-module-level-items = true
