[package]
name = "dva"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet.workspace = true
openzeppelin_token.workspace = true
openzeppelin_account.workspace = true
openzeppelin_introspection.workspace = true
openzeppelin_utils.workspace = true
roles = { path = "../roles" }
token = { path = "../token" }
registry = { path = "../registry" }
storage = { path = "../storage" }

[dev-dependencies]
snforge_std.workspace = true
assert_macros.workspace = true
factory = { path = "../factory" }

[[target.starknet-contract]]
sierra = true
build-external-contracts = ["onchain_id_starknet::*", "factory::*", "registry::*", "roles::*", "compliance::*", "token::*", "mocks::*"]

[tool]
fmt.workspace = true

[lib]
name = "dva"
