[package]
name = "dva"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet.workspace = true
openzeppelin_token.workspace = true
openzeppelin_account.workspace = true
openzeppelin_introspection.workspace = true
roles = { path = "../roles" }
token = { path = "../token" }
registry = { path = "../registry" }
storage = { path = "../storage" }

[[target.starknet-contract]]
sierra = true

[tool]
fmt.workspace = true

[lib]
name = "dva"
