[package]
name = "mocks"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet.workspace = true
compliance = { path = "../compliance"}

[dev-dependencies]
snforge_std.workspace = true

[[target.starknet-contract]]
sierra = true

[tool]
fmt.workspace = true

[lib]
name= "mocks"