[package]
name = "factory"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet.workspace = true
openzeppelin_access.workspace = true
openzeppelin_token.workspace = true
roles = { path = "../roles"}
compliance = { path = "../compliance"}
registry = { path = "../registry"}
onchain_id = { path = "../onchain_id"}
token = { path = "../token"}

[dev-dependencies]
snforge_std.workspace = true

[[target.starknet-contract]]
sierra = true

[tool]
fmt.workspace = true

[lib]
name= "factory"