[package]
name = "factory"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet.workspace = true
openzeppelin_access.workspace = true
openzeppelin_token.workspace = true
openzeppelin_upgrades.workspace = true
roles = { path = "../roles"}
compliance = { path = "../compliance"}
registry = { path = "../registry"}
onchain_id_starknet.workspace = true
token = { path = "../token"}
mocks = { path = "../mocks"}
snforge_std.workspace = true

[[target.starknet-contract]]
sierra = true
build-external-contracts = ["onchain_id_starknet::*", "registry::*", "roles::*", "compliance::*", "token::*", "mocks::*"]
allowed-libfuncs-list.name = "all"

[tool]
fmt.workspace = true

[lib]
name= "factory"