[package]
name = "registry"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet.workspace = true
storage = { path = "../storage"}
roles = { path = "../roles"}
factory = { path = "../factory"}
onchain_id_starknet.workspace = true
openzeppelin_access.workspace = true
openzeppelin_upgrades.workspace = true

[dev-dependencies]
snforge_std.workspace = true

[[target.starknet-contract]]
sierra = true
build-external-contracts = ["onchain_id_starknet::*", "factory::*", "roles::*", "compliance::*", "token::*", "mocks::*"]

[tool]
fmt.workspace = true

[lib]
name= "registry"