[package]
name = "compliance"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet.workspace = true

[[target.starknet-contract]]
sierra = true

[tool]
fmt.workspace = true

[lib]
name= "compliance"