[package]
name = "compliance"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet.workspace = true
token =  { path = "../token"}
roles = { path = "../roles"}
registry = { path = "../registry"}
storage = { path = "../storage"}
openzeppelin_access.workspace = true
openzeppelin_upgrades.workspace = true
openzeppelin_token.workspace = true
snforge_std.workspace = true

[[target.starknet-contract]]
sierra = true

[tool]
fmt.workspace = true

[lib]
name= "compliance"